In [14]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import inspect

In [15]:
 csv_file = "data-csv/penalty_kicks.csv"
penalty_kicks_df = pd.read_csv(csv_file)
penalty_kicks_df.head()

,key_id,penalty_kick_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,team_code,home_team,away_team,player_id,family_name,given_name,shirt_number,converted
0,1,PK-001,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-02728,Kaltz,Manfred,20,1
1,2,PK-002,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-02216,Breitner,Paul,3,1
2,3,PK-003,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-09412,Stielike,Uli,15,0
3,4,PK-004,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-05795,Littbarski,Pierre,7,1
4,5,PK-005,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-08975,Rummenigge,Karl-Heinz,11,1

In [16]:
new_penalty_kicks_df = penalty_kicks_df[['penalty_kick_id','tournament_id','match_id', 'match_name','match_date', 'stage_name','team_id','team_name','player_id','family_name','given_name','shirt_number','converted']].copy()

In [17]:
new_penalty_kicks_df = new_penalty_kicks_df.loc[(new_penalty_kicks_df['match_date'] > '1997-12-31')] 
new_penalty_kicks_df.head()

,penalty_kick_id,tournament_id,match_id,match_name,match_date,stage_name,team_id,team_name,player_id,family_name,given_name,shirt_number,converted
106,PK-107,WC-1998,M-1998-56,Argentina v England,1998-06-30,round of 16,T-03,Argentina,P-08146,Berti,Sergio,16,1
107,PK-108,WC-1998,M-1998-56,Argentina v England,1998-06-30,round of 16,T-03,Argentina,P-07013,Crespo,Hernán,19,0
108,PK-109,WC-1998,M-1998-56,Argentina v England,1998-06-30,round of 16,T-03,Argentina,P-05303,Verón,Juan Sebastián,11,1
109,PK-110,WC-1998,M-1998-56,Argentina v England,1998-06-30,round of 16,T-03,Argentina,P-08547,Gallardo,Marcelo,20,1
110,PK-111,WC-1998,M-1998-56,Argentina v England,1998-06-30,round of 16,T-03,Argentina,P-09897,Ayala,Roberto,2,1

In [ ]:
#Connect to local database

protocol = 'postgresql'
username = '<user name>'
password = '<password>'
host = 'localhost'
port = 5432
database_name = '#databasename#'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)
insp = inspect(engine)

In [ ]:
insp.get_table_names()

In [ ]:
# Use pandas to load csv converted DataFrame into database

new_customer_data_df.to_sql(name='goals', con=engine, if_exists='append', index=False)