In [2]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import inspect

In [3]:
 csv_file = "data-csv/penalty_kicks.csv"
penalty_kicks_df = pd.read_csv(csv_file)
penalty_kicks_df.head()

,key_id,penalty_kick_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,team_code,home_team,away_team,player_id,family_name,given_name,shirt_number,converted
0,1,PK-001,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-02728,Kaltz,Manfred,20,1
1,2,PK-002,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-02216,Breitner,Paul,3,1
2,3,PK-003,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-09412,Stielike,Uli,15,0
3,4,PK-004,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-05795,Littbarski,Pierre,7,1
4,5,PK-005,WC-1982,1982 FIFA World Cup,M-1982-50,West Germany v France,1982-07-08,semi-finals,not applicable,T-82,West Germany,DEU,1,0,P-08975,Rummenigge,Karl-Heinz,11,1

In [4]:
new_penalty_kicks_df = penalty_kicks_df[['penalty_kick_id','tournament_id','match_id', 'match_name','match_date', 'stage_name','team_id','team_name','player_id','family_name','given_name','shirt_number','converted']].copy()

new_penalty_kicks_df.head()

,penalty_kick_id,tournament_id,match_id,match_name,match_date,stage_name,team_id,team_name,player_id,family_name,given_name,shirt_number,converted
0,PK-001,WC-1982,M-1982-50,West Germany v France,1982-07-08,semi-finals,T-82,West Germany,P-02728,Kaltz,Manfred,20,1
1,PK-002,WC-1982,M-1982-50,West Germany v France,1982-07-08,semi-finals,T-82,West Germany,P-02216,Breitner,Paul,3,1
2,PK-003,WC-1982,M-1982-50,West Germany v France,1982-07-08,semi-finals,T-82,West Germany,P-09412,Stielike,Uli,15,0
3,PK-004,WC-1982,M-1982-50,West Germany v France,1982-07-08,semi-finals,T-82,West Germany,P-05795,Littbarski,Pierre,7,1
4,PK-005,WC-1982,M-1982-50,West Germany v France,1982-07-08,semi-finals,T-82,West Germany,P-08975,Rummenigge,Karl-Heinz,11,1

In [63]:
new_penalty_kicks_df = new_penalty_kicks_df.loc[(new_penalty_kicks_df['match_date'] > '1997-12-31')]

In [64]:
knock_out = ['final','semi-finals','quarter-finals']

new_penalty_kicks_df = new_penalty_kicks_df.loc[new_penalty_kicks_df['stage_name'].isin(knock_out)]

In [65]:
new_penalty_kicks_df['year'] = pd.DatetimeIndex(new_penalty_kicks_df['match_date']).year

In [68]:
new_penalty_kicks_df.groupby(['team_name','year','family_name']).sum()

                            shirt_number  converted
team_name year family_name
Argentina 2006 Ayala                   2          0
               Cambiasso               5          0
               Cruz                   20          1
               Rodríguez              18          1
          2014 Agüero                 20          1
...                                  ...        ...
Uruguay   2010 Abreu                  13          1
               Forlán                 10          1
               Pereira                16          0
               Scotti                 19          1
               Victorino               6          1

[85 rows x 2 columns]