In [4]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import inspect

In [5]:
 csv_file = "data-csv/player_appearances.csv"
player_appearances = pd.read_csv(csv_file)
player_appearances.head()

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,away_team,player_id,family_name,given_name,shirt_number,position_name,position_code,starter,substitute,captain
0,1,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,0,P-02951,Calderón,Ignacio,1,goal keeper,GK,1,0,0
1,2,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,0,P-09033,Peña,Gustavo,3,defender,DF,1,0,1
2,3,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,0,P-02770,Pérez,Mario,5,defender,DF,1,0,0
3,4,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,0,P-04709,Hernández,Guillermo,6,midfielder,MF,1,0,0
4,5,WC-1970,1970 FIFA World Cup,M-1970-01,Mexico v Soviet Union,1970-05-31,group stage,Group 1,T-44,Mexico,...,0,P-01956,Salgado,Horacio López,10,forward,FW,1,0,0

In [7]:
new_player_appearances = player_appearances[['player_id', 'tournament_id','match_id', 'team_id','starter','substitute','captain']].copy()

new_player_appearances.head()

  player_id tournament_id   match_id team_id  starter  substitute  captain
0   P-02951       WC-1970  M-1970-01    T-44        1           0        0
1   P-09033       WC-1970  M-1970-01    T-44        1           0        1
2   P-02770       WC-1970  M-1970-01    T-44        1           0        0
3   P-04709       WC-1970  M-1970-01    T-44        1           0        0
4   P-01956       WC-1970  M-1970-01    T-44        1           0        0