In [5]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import inspect

In [6]:
 csv_file = "data-csv/tournaments.csv"
tournaments = pd.read_csv(csv_file)
tournaments.head()

,key_id,tournament_id,tournament_name,year,start_date,end_date,host_country,winner,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,1,WC-1930,1930 FIFA World Cup,1930,1930-07-13,1930-07-30,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,2,WC-1934,1934 FIFA World Cup,1934,1934-05-27,1934-06-10,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,3,WC-1938,1938 FIFA World Cup,1938,1938-06-04,1938-06-19,France,Italy,0,15,0,0,0,1,1,1,1,1
3,4,WC-1950,1950 FIFA World Cup,1950,1950-06-24,1950-07-16,Brazil,Uruguay,0,13,1,0,1,0,0,0,0,0
4,5,WC-1954,1954 FIFA World Cup,1954,1954-06-16,1954-07-04,Switzerland,West Germany,0,16,1,0,0,0,1,1,1,1

In [7]:
new_tournaments = tournaments[['tournament_id', 'tournament_name','year', 'host_country','winner','host_won','count_teams','group_stage','second_group_stage','final_round','round_of_16','quarter_finals','semi_finals','third_place_match','final']].copy()

new_tournaments.head()

,tournament_id,tournament_name,year,host_country,winner,host_won,count_teams,group_stage,second_group_stage,final_round,round_of_16,quarter_finals,semi_finals,third_place_match,final
0,WC-1930,1930 FIFA World Cup,1930,Uruguay,Uruguay,1,13,1,0,0,0,0,1,0,1
1,WC-1934,1934 FIFA World Cup,1934,Italy,Italy,1,16,0,0,0,1,1,1,1,1
2,WC-1938,1938 FIFA World Cup,1938,France,Italy,0,15,0,0,0,1,1,1,1,1
3,WC-1950,1950 FIFA World Cup,1950,Brazil,Uruguay,0,13,1,0,1,0,0,0,0,0
4,WC-1954,1954 FIFA World Cup,1954,Switzerland,West Germany,0,16,1,0,0,0,1,1,1,1